---
title: "Papers"
---

# 2024

**Elmokadem A**, Wiens M, Knab T, Utsey K, Callisto S, Kirouac D. Hierarchical deep compartment modeling: A workflow to leverage machine learning and Bayesian inference for hierarchical pharmacometric modeling. Clinical and Translational Science, October. [https://doi.org/10.1111/cts.70045](https://doi.org/10.1111/cts.70045). 

# 2023

**Elmokadem A**, Zhang Y, Knab T, Jordie E, Gillespie WR. Bayesian PBPK Modeling using R/Stan/Torsten and Julia/SciML/Turing.jl. CPT: Pharmacometrics & Systems Pharmacology, January. [https://doi.org/10.1002/psp4.12926](https://doi.org/10.1002/psp4.12926). 

# 2021

Chigutsa E, Jordie E, Riggs M, Nirula A, **Elmokadem A**, Knab T, and Chien JY. A Quantitative Modeling and Simulation Framework to Support Candidate and Dose Selection of Anti-SARS-CoV-2 Monoclonal Antibodies to Advance Bamlanivimab into a First-in-Human Clinical Trial. Clinical Pharmacology & Therapeutics, October. [https://doi.org/10.1002/cpt.2459](https://doi.org/10.1002/cpt.2459). This manuscript received the “Outstanding Research Manuscript Award” from the International Society of Pharmacometrics (ISoP) in October 2022.

Bruno CD, **Elmokadem A**, Housand C, Jordie EB, Chow C, Laughren TP, and Greenblatt DJ. Impact of Obesity on Brexpiprazole Pharmacokinetics: Proposal for Improved Initiation of Treatment. Journal of Clinical Pharmacology, August. [https://doi.org/10.1002/jcph.1947](https://doi.org/10.1002/jcph.1947).

**Elmokadem A**, Bruno CD, Housand C, Jordie EB, Chow C, Lesko LJ, and Greenblatt DJ. Brexpiprazole Pharmacokinetics in CYP2D6 Poor Metabolizers: Using Physiologically Based Pharmacokinetic Modeling to Optimize Time to Effective Concentrations. Journal of Clinical Pharmacology, July. [https://doi.org/10.1002/jcph.1946](https://doi.org/10.1002/jcph.1946).

Johnston CK, Eudy-Byrne RJ, **Elmokadem A**, Nock V, Marquard J, Soleymanlou N, Riggs MM, and Liesenfeld KH. A Model-Informed Drug Development (MIDD) Approach for a Low Dose of Empagliflozin in Patients with Type 1 Diabetes. Pharmaceutics, April. [https://doi.org/10.3390/pharmaceutics13040485](https://doi.org/10.3390/pharmaceutics13040485).



# 2020

Utsey K, Gastonguay MS, Russell S, Freling R, Riggs MM, and **Elmokadem A**. Quantification of the Impact of Partition Coefficient Prediction Methods on PBPK Model Output Using a Standardized Tissue Composition. Drug Metabolism and Disposition, July. https://doi.org/10.1124/dmd.120.090498. The paper was listed among the “Papers Worth Reading” by the International Society of Pharmacometrics (ISoP) newsletter issued in September 2020 [https://doi.org/10.1124/dmd.120.090498](https://doi.org/10.1124/dmd.120.090498).

# 2019

Perkins BA,  Soleymanlou N,  Rosenstock J,  Skyler JS,  Laffel LM,  Liesenfeld KH,  Neubacher D, Riggs MM,  Johnston CK,  Eudy‐Byrne RJ, **Elmokadem A**, George JT, Marquard J,  and Nock V. Low‐dose empagliflozin as adjunct to insulin therapy in type 1 diabetes: A valid modelling and simulation analysis to confirm efficacy. Diabetes, Obesity and Metabolism, December. [https://doi.org/10.1111/dom.13945](https://doi.org/10.1111/dom.13945).

**Elmokadem A**, Riggs MM, and Baron KB. Quantitative Systems Pharmacology and Physiologically-Based Pharmacokinetic Modeling With mrgsolve: A Hands-On Tutorial. CPT: Pharmacometrics & Systems Pharmacology, October. [https://doi.org/10.1002/psp4.12467](https://doi.org/10.1002/psp4.12467).

Ji Y and **Elmokadem A**. Single-Molecule Localization Microscopy as Nonlinear Inverse Problem. Proceedings of the National Academy of Sciences of the United States of America, September. [https://doi.org/10.1073/pnas.1912634116](https://doi.org/10.1073/pnas.1912634116).


# 2015

**Elmokadem A** and Yu J. Optimal Drift Correction for Superresolution Localization Microscopy with Bayesian Inference. Biophys J. 109(9), 1772-1780. [https://doi.org/10.1016/j.bpj.2015.09.017](https://doi.org/10.1016/j.bpj.2015.09.017)

